package atm27.controller;

import java.io.IOException;

import atm27.domain.ATM;
import atm27.domain.Session;
import atm27.utils.ATMUtils;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.layout.BorderPane;

public class IndexController {
	//通过工具类获取单例atm
	private ATM atm = ATMUtils.getATM();
	@FXML
	private BorderPane indexBP;
	@FXML
	private Button withdrawBt;
	@FXML
	private Button selectCashBt;
	@FXML
	private Button exit;

	// Event Listener on Button[#withdrawBt].onAction
	@FXML
	public void withdraw(ActionEvent event) throws IOException {
		Parent root = FXMLLoader.load(getClass().getResource("/atm27/view/withdraw.fxml"));
		Label label = (Label)root.lookup("#money"); 
		
		//通过ATM调用查询余额方法
		double balance=atm.getAccountBalance();
		
		if(label!=null){
			label.setText(balance+"");
		}
		InsertCardController mainPage = (InsertCardController) Session.getSession().get("mainPage");
		mainPage.getBigBP().setCenter(new BorderPane(root));
		
		
	}
	// Event Listener on Button[#selectCashBt].onAction
	@FXML
	public void selectCash(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#exit].onAction
	@FXML
	public void exit(ActionEvent event) {
		//界面操作
		InsertCardController mainPage = (InsertCardController) Session.getSession().get("mainPage");
		mainPage.rollToFirst();
	}
}
